# Source format
from: markdown
# Destination format
to: pdf

# Output file path
output-file: LSST_PXI_SoftwareDocumentation.pdf

# Set the template for the document
template: Resources/eisvogel.tex

# Set appropriate variables
variables:
  colorlinks: true
  fontsize: 12pt
  titlepage: true
  toc-own-page: true
  listings-no-page-break: false
  listings-disable-line-numbers: true
  classoption: oneside
  book: true
  footer-center: ''

# Set the appropriate metadata
metadata:
  title: 'LSST PXI Software Documentation'
  subtitle: ''
  author: 'Julen Garcia'
  lang: en-EN

# Set resource path
resource-path: ["Resources"]

# Auto-Number the sections
number-sections: true

# Generate an index
table-of-contents: true
toc-depth: 3

# Use listings package for LaTeX code blocks
listings: true

# New page on each chapter
top-level-division: chapter

